### ISSUE TITLE
SDA and SCL Pins

### ISSUE THREAD

**Issue by peekyuk** [mark-gladding/packed-font#1]
Very Nice. Only works on my Raspberry PICO W using the GPO pin numbers hard coded on line 61 of  PiicoDev_Unified.py......  which are  pins  8 and 9, which it seems are the default pins for SDA and SCL for your application. I found out after having trawled through the code.  perhaps the readme instructions should  advise on pin numbers  to use ?

**Comment by CoreProduction** [comment]
Isn't it nice! 😄 This has got to be my favourite [user-contribution](https://core-electronics.com.au/guides/piicodev/piicodev-community-contributions/) to the PiicoDev ecosystem.

The pins thing is more of an issue with [PiicoDev](https://github.com/CoreElectronics/CE-PiicoDev-Unified) than with packed-font... Mark's off the hook for this one 😅 

Rather than hard coding the pins, you should be able to specify bus, pins and frequency using the [OLED initialiser](https://github.com/CoreElectronics/CE-PiicoDev-SSD1306-MicroPython-Module?tab=readme-ov-file#create_piicodev_ssd1306bus-freq-sda-scl-addr0x3c)
`create_PiicoDev_SSD1306(bus=, freq=, sda=, scl=, addr=0x3C)` where all terms must be defined by you - if you don't provide a definition for all 4 parameters (bus, freq, sda) and scl then it may revert to the defaults.

**Comment by peekyuk** [comment]
Thanks for the reply. I realised the issue was not with Packed Font after posting, but left it as this is too good for folks to miss out on due to pin config misunderstandings.
